# Generated by Django 4.2.7 on 2023-11-26 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка книги')),
                ('title', models.CharField(default='', max_length=50, verbose_name='Название')),
                ('author', models.CharField(default='', max_length=20, verbose_name='Автор книги')),
                ('description', models.TextField(verbose_name='Описание книги')),
                ('price', models.IntegerField(verbose_name='Цена книги')),
            ],
        ),
    ]
